name: api test and deploy
on:
  push:
    branches:
      - main
    paths:
      - 'packages/api/**'
  pull_request:
    paths:
      - 'packages/api/**'
jobs:
  # run tests on pr
  test:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo yarn install

      - name: test
        run: |
          echo yarn test

  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    name: Deploy to staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: deploy staging
        run: |
          echo yarn deploy staging

  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    name: Deploy to production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo yarn deploy production
