name: api-test-and-deploy
on:
  push:
    branches:
      - main
    paths:
      - 'packages/api/**'
  pull_request:
    paths:
      - 'packages/api/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      - name: Dump GitHub context
        id: github_context_step
        run: |
          echo '${{ toJSON(github) }}'
      - name: Install dependencies
        run: |
          echo yarn install
      - name: test
        run: |
          echo yarn test

  deploy-staging:
    runs-on: ubuntu-latest
    needs: test
    environment: staging
    name: Deploy to staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: deploy staging
        run: |
          echo yarn deploy staging

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production
    name: Deploy to production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo yarn deploy production
      - name: Post github workflow stats to server
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo merge to main iso date ${{ github.event.head_commit.timestamp }}
          echo merge to main unix timestamp $(date -d ${{ github.event.head_commit.timestamp }} +%s)
          echo deploy success timestamp $(date)
          echo deploy success unix timestamp $(date +%s)
          curl --get pie.dev/get \
          -d workflow=$GITHUB_WORKFLOW \
          -d run_number=${{ github.run_number }} \
          -d run_attempt=${{ github.run_attempt }} \
          -d start_timestamp=$(date -d ${{ github.event.head_commit.timestamp }} +%s) \
          -d end_timestamp=$(date +%s)
